SIGNIFICANCE_HIGH = 'HIGH'
TENDRL_GRAFANA_SEVERITY_MAP = {
    'alerting': 'WARNING',
    'ok': 'INFO',
}
TENDRL = 'Tendrl'
ALERT_SOURCE = 'GRAFANA'
CLUSTER = 'cluster'
NODE = 'node'
ALERT_TYPE = 'UTILIZATION'
